name: Build CompatNoCheatPlus

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 8
        uses: actions/setup-java@main
        with:
          java-version: 8
          distribution: temurin
      - name: Download BuildTools
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Build Spigot 1.8.8
        run: java -jar BuildTools.jar --rev 1.8.8
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin
      - name: Build CompatNoCheatPlus
        run: mvn clean package

      - name: Release CompatNoCheatPlus
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "CompatNoCheatPlus"
          automatic_release_tag: "cncp"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*.jar"
          prerelease: true
